# Generated by Django 4.0 on 2022-01-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='present_file_name',
            field=models.CharField(max_length=200),
        ),
    ]
