# Generated by Django 4.0 on 2022-01-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classroomApp', '0002_alter_lecture_present_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroomApp.mark'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classroomApp.lecture'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_mark', to='classroomApp.homework'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_rel', to='auth.user'),
        ),
    ]
